### PR TITLE
Fixes #10 (clicking "next block" on last block should ask cothority for latest block)

### LINKED ISSUE #10: clicking "next block" on last block should ask cothority for latest block
If for example block 21 was the latest when the page was loaded, and new blocks arrive on the chain, clicking "next block" on block 21 should still work. right now it silently fails to discover the new blocks.

### PR DESCRIPTION
**Pull request by nkcr**
Now when clicking on the "next" button when we are at the last local loaded block, the app queries the last block of the skipchain and checks if new blocks were added. If it's the case, we load the I+1 block.

Fixes #10

### CODE REVIEW

File: src/components/BlockInfo.vue [hunk 1]
```diff
@@ -155,9 +158,36 @@ export default {
...
+      if (i > this.blocks.length - 1) {
+        this.socket.getLatestBlock(hex2Bytes(this.$route.params.chain), false).then(
+          (latestBlock) => {
+            if (bytes2Hex(latestBlock.hash) !== bytes2Hex(this.block.hash)) {
+              this.getBlockByIndex(i).then(_ => {
+                this.$router.push(`/${this.$route.params.chain}/blocks/${i}`)
+              })
+            } else {
+              this.infos.next = 'No new blocks detected.'
+              setTimeout(_ => {
```
Comment (Gilthoniel) [inline src/components/BlockInfo.vue]: () => { ... }

File: src/components/BlockInfo.vue [hunk 2]
```diff
@@ -155,9 +158,36 @@ export default {
...
+      // In the case we want to fetch a block whose index is greater than the
+      // current number of loaded block, we have to check if one or more blocks
+      // have been added. To do so, we query the last stored block in the chain
+      // and compare its hash with our last local stored block. If the hash
+      // match, we can be sur that no new blocks were added. Otherwise we can
+      // safely fetch the i+1 block.
+      if (i > this.blocks.length - 1) {
+        this.socket.getLatestBlock(hex2Bytes(this.$route.params.chain), false).then(
+          (latestBlock) => {
+            if (bytes2Hex(latestBlock.hash) !== bytes2Hex(this.block.hash)) {
```
Comment (Gilthoniel) [inline src/components/BlockInfo.vue]: Both .hash should be Buffers so you can use `!latestBlock.Hash.Equals(this.block.hash)` to avoid the conversion

File: src/components/BlockInfo.vue [hunk 3]
```diff
@@ -155,9 +158,36 @@ export default {
...
+              this.getBlockByIndex(i).then(_ => {
```
Comment (Gilthoniel) [inline src/components/BlockInfo.vue]: () => { ... }

**Comment by nkcr** [comment]
Thanks for the good comments, should be fixed in 0e4dbac8f5539492fa1f2ddf060a687def40e76b !

File: src/Explorer.vue [hunk 4]
```diff
@@ -47,7 +47,10 @@ export default {
           if (!shouldNotUpdateBlocks) {
             this.blocks.splice(i, 1, { ...skipblock, loaded: true })
           }
-          return skipblock
```
[the remark this answers is not in the document]
Comment (Gilthoniel) [reply src/Explorer.vue]: @nkcr careful to restore the removed line.

File: src/components/BlockInfo.vue [hunk 5]
```diff
@@ -169,4 +199,14 @@ export default {
 code::before {
   content: '';
 }
+h3.block-info {
+  position: relative;
+}
+  h3.block-info > p {
```
Comment (Gilthoniel) [inline src/components/BlockInfo.vue]: Is it Github that is putting a weird tabulation here ?

Comment (nkcr) [reply src/components/BlockInfo.vue]: Just an [old habit](https://css-tricks.com/different-ways-to-format-css/#article-header-id-1) with css files. But yes, probably not needed here.
